name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: "0 18 * * *" # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in blog's posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://rss.csdn.net/qq_44973159/rss/map"
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email "2645929971@qq.com"
          git add -A .
          git commit -m "last-blog-update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push