name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: lizuoqun
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email "2645929971@qq.com"
          git add -A .
          git commit -m "metrics update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push